In [22]:
import pandas as pd

In [23]:
with open('batting2022.csv') as f:
    print(f)

<_io.TextIOWrapper name='batting2022.csv' mode='r' encoding='UTF-8'>

In [24]:
df = pd.read_csv("batting2022.csv", encoding='ISO-8859-1')
pd.set_option('display.max_columns', None)

In [25]:
df

,Rk,Name,Age,Tm,Lg,G,PA,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,PosÊSummary,Name-additional
0,1,CJÊAbrams*,21,TOT,NL,90,302,284,33,70,12,2,2,21,7,4,5,50,0.246,0.280,0.324,0.604,76.0,92,5,9,2,2,0,64/H9D,abramcj01
1,2,CJÊAbrams*,21,SDP,NL,46,139,125,16,29,5,0,2,11,1,2,4,27,0.232,0.285,0.320,0.605,77.0,40,4,6,2,2,0,64/H9D,abramcj01
2,3,CJÊAbrams*,21,WSN,NL,44,163,159,17,41,7,2,0,10,6,2,1,23,0.258,0.276,0.327,0.603,75.0,52,1,3,0,0,0,6/H,abramcj01
3,4,AlbertÊAbreu,26,TOT,AL,1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1,abreual01
4,5,AlbertÊAbreu,26,KCR,AL,1,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,/1,abreual01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
982,983,SebyÊZavala,28,CHW,AL,61,205,178,22,48,14,0,2,21,0,0,19,64,0.270,0.347,0.382,0.729,107.0,68,1,3,3,2,0,2/H3D,zavalse01
983,984,BradleyÊZimmer*,29,TOT,MLB,109,117,105,18,13,5,0,2,5,3,2,5,45,0.124,0.207,0.229,0.435,25.0,24,0,6,1,0,0,8H/D9,zimmebr01
984,985,BradleyÊZimmer*,29,TOR,AL,100,101,89,14,9,4,0,2,5,3,2,5,41,0.101,0.200,0.213,0.413,19.0,19,0,6,1,0,0,8H/D9,zimmebr01
985,986,BradleyÊZimmer*,29,PHI,NL,9,16,16,4,4,1,0,0,0,0,0,0,4,0.250,0.250,0.313,0.563,58.0,5,0,0,0,0,0,/8H,zimmebr01
986,987,MikeÊZunino,31,TBR,AL,36,123,115,7,17,3,0,5,16,0,0,6,46,0.148,0.195,0.304,0.499,44.0,35,2,1,0,1,0,2/H,zuninmi01